name: Build and Deploy nvrx-rk3588

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # This will use your self-hosted runner
    env:  # Environment variables for the entire job
      GIT_HOME_DIR: "/home/neeldharsandiya/neel/selfhostedrunners/actions-runner/ndworkspace"
  
    steps:
      - name: Preparing Environment
        run: |
          echo "Set/Export necessary variables..."
          echo "CURRENT_GITHUB_REPOSITORY=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-app
          submodules: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
    
      - name: Download build dependencies from JFrog
        run: |          
          echo "Downloading Dependencies..."
          curl -u "admin:cmVmdGtuOjAxOjE3NjU5NzQ3ODE6Zndrc0ZWOGd3RzRnWnZLU1JkOGlod1Q2bFE3" -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/Device_Client_Setup_8.7.52.exe" "http://192.168.27.92:8082/ui/login/ipvs-nvr-device-client-prod-release/8.7.52/Device_Client_Setup_8.7.52.exe"
          curl -u "admin:Admin@123" -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/platform_upgrade.zip" "http://192.168.27.92:8082/ui/login/ipvs-bsp-nvrx-rk3588-prod-release/8.7.0/platform_upgrade.zip"
          curl -u "admin:Admin@123" -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/host.tar.xz" "http://192.168.27.92:8082/ui/login/ipvs-bsp-nvrx-rk3588-prod-release/8.7.0/host.tar.xz"
      
      - name: Compile and Prepare Package
        run: |
          echo "Change directory & apply Make command"
          echo "Path: $GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY"
          cd "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY" && ls -al && make BOARD_TYPE=RK3588_NVRH RELEASE_TYPE=QA PASSWORD=neel release
      
      - name: Upload release artifacts to JFrog
        run: |
          echo "Uploading Artifacts..."
          cd "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build"
          curl -u "admin:Neel@2822" -T "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/NVR_RK3588H-2.2.0.zip" "http://192.168.27.92:8082/artifactory/ipvs-nvrx-prod-release/2.2.0/rk3588h/field/NVR_RK3588H-2.2.0.zip"
          echo "Artifacts Uploaded Successfully"
          
