name: Build and Deploy nvrx-rk3588

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # This will use your self-hosted runner  
    
    steps:
      - name: Environment Information
        run: |
          echo "$GITHUB_WORKSPACE"
      
      - name: Checkout Github Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvrx
          submodules: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
    
      - name: Download build dependencies from JFrog
        run: |          
          echo "Downloading Dependencies..."
          mkdir -p $GITHUB_WORKSPACE/build/deps 
          curl -u "admin:Admin@123" -o "$GITHUB_WORKSPACE/src/Application/Build/Device_Client_Setup_8.7.52.exe" "http://192.168.27.92:8082/artifactory/ipvs-nvr-device-client-prod-release/8.7.52/Device_Client_Setup_8.7.52.exe"
          curl -u "admin:Admin@123" -o "$GITHUB_WORKSPACE/src/Application/Build/platform_upgrade.zip" "http://192.168.27.92:8082/artifactory/ipvs-bsp-nvrx-rk3588-prod-release/8.7.0/platform_upgrade.zip"
      
      - name: Compile and Prepare Package
        run: |
          echo "Change directory & apply Make command"
          cd "$GITHUB_WORKSPACE" && ls -al && make BOARD_TYPE=RK3588_NVRH RELEASE_TYPE=QA PASSWORD=neel release
      
      - name: Upload release artifacts to JFrog
        id: upload-artifact
        run: |
          echo "Uploading Artifacts..."
          ARTIFACT_PATH="http://192.168.27.92:8082/artifactory/ipvs-nvrx-prod-release/2.2.0/rk3588h/field/nvrx_rk3588h-2.2.0.zip"
          curl -u "admin:Admin@123" -T "$GITHUB_WORKSPACE/src/Application/Build/nvrx_rk3588h-2.2.0.zip" "$ARTIFACT_PATH"
          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
          echo "Artifacts Uploaded Successfully"
        continue-on-error: true

      - name: Trigger Notify Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const artifactUploaded = ${'{'} steps['upload-artifact'].outcome === 'success' ${'}'};
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "notify.yaml",
              ref: context.ref,
              inputs: {
                artifact_path: artifactUploaded ? process.env.ARTIFACT_PATH : '',
                artifact_uploaded: artifactUploaded.toString()
              }
            })
