name: jf-test

on:
  workflow_dispatch:

jobs:
  create_zip_and_upload:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a sample file
      run: |
        echo "This is a sample file content" > sample-file.txt

    - name: Zip the file
      run: |
        zip sample-file.zip sample-file.txt

    - name: Upload to JFrog Artifactory
      run: |
          ping -c 4 172.16.0.213 || echo "Artifactory is unreachable"
          curl -k -u "${{ vars.JFROG_USER }}:${{ vars.JFROG_PASSWORD }}" -T sample-file.zip "${{ vars.JFROG_URL }}/from-github-actions/sample-file.zip"
    
    #- name: Set up JFrog CLI (v1.0.0)
    #  uses: jfrog/setup-jfrog-cli-action@v1.0.0
          
    #- name: Upload to JFrog Artifactory
    #  env:
    #    JFROG_URL: ${{ secrets.JFROG_URL }}  # URL for your JFrog instance
    #    JFROG_USERNAME: ${{ secrets.JFROG_USER }}  # JFrog Username
    #    JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}  # JFrog Password
    #  run: |
    #    jfrog rt config --url $JFROG_URL --user $JFROG_USERNAME --password $JFROG_PASSWORD
    #    jfrog rt upload "sample-file.zip" "from-github-actions/"
