name: Nightly Build on Feature Branches

on:
  schedule:
    - cron: '07 20 * * *'  # Runs every night at midnight UTC
  push:
    branches:
      - 'feature-*'  # Matches all branches starting with 'feature-'
  pull_request:
    branches:
      - 'feature-*'  # Runs on PRs to any feature branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: | 
          echo "Building branch: ${GITHUB_REF#refs/heads/}"
