name: email notification...

on:
  push:
    tags:
      - '*'
  delete:
    tags:
      - '*'
    branches:
      - '*'
  create:
    branches:
      - '*'
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Details
        id: event-details
        run: |
          if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
            echo "type=Tag" >> $GITHUB_ENV
            echo "ref=${{ github.event.ref }}" >> $GITHUB_ENV
            echo "subject=New Tag Created: ${{ github.event.ref }}" >> $GITHUB_ENV
            echo "url=${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.ref_type }}" == "branch" ]]; then
            echo "type=Branch" >> $GITHUB_ENV
            echo "ref=${{ github.event.ref }}" >> $GITHUB_ENV
            echo "subject=New Branch Created: ${{ github.event.ref }}" >> $GITHUB_ENV
            echo "url=${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.ref }}" >> $GITHUB_ENV
          fi
      - name: Send Gmail Notification
        uses: dawidd6/action-send-mail@v3
        with:
          # server details
          #server_address: smtp.gmail.com
          #server_port: 587
          #username: ${{ secrets.GMAIL_ID }}
          #password: ${{ secrets.GMAIL_PASSWORD }}
          
          # format
          to: 'pragya.dayal@matrixcomsec.com' # recipient's email
          #from: ${{ secrets.GMAIL_ID }}
          from: neeldharsandiya123@gmail.com
          subject: ${{ env.subject }}
          body: |
            A new ${{ env.type }} named '${{ env.ref }}' was created in the repository.
            You can view it here: ${{ env.url }}
          

