name: email notification...

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  delete:
    tags:
      - '*'
    branches:
      - '*'
  create:
    branches:
      - '*'
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Details
        id: event-details
        run: |
          if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
            echo "type=Tag" >> $GITHUB_ENV
            echo "ref=${{ github.event.ref }}" >> $GITHUB_ENV
            echo "subject=New Tag Created: ${{ github.event.ref }}" >> $GITHUB_ENV
            echo "url=${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.ref_type }}" == "branch" ]]; then
            echo "type=Branch" >> $GITHUB_ENV
            echo "ref=${{ github.event.ref }}" >> $GITHUB_ENV
            echo "subject=New Branch Created: ${{ github.event.ref }}" >> $GITHUB_ENV
            echo "url=${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.ref }}" >> $GITHUB_ENV
          fi

      - name: Check for Artifact URL
        run: |
          if [[ -n "${{ github.event.inputs.artifact_url }}" ]]; then
            echo "artifact_url=${{ github.event.inputs.artifact_url }}" >> $GITHUB_ENV
          fi
        
      - name: Send Gmail Notification
        uses: dawidd6/action-send-mail@v3
        with:
          # server details
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_ID }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          
          # format
          from: ${{ secrets.GMAIL_ID }}
          to: 'neel.dharsandiya@matrixcomsec.com'
          subject: ${{ env.subject }}
          body: |
            A new ${{ env.type }} named '${{ env.ref }}' was created in the repository.
            You can view it here: ${{ env.url }}

            ${% if env.artifact_url %}
            Additionally, the artifact has been uploaded to JFrog and is available at:
            ${{ env.artifact_url }}
            ${% endif %}
          

