name: email notification...

on:
  workflow_dispatch:
    inputs:
      artifact_path:
        description: "Path of the uploaded artifact in JFrog"
        required: false
      artifact_uploaded:
        description: "Whether the artifact was successfully uploaded"
        required: true
      repo_name:
        description: "Repository name"
        required: true
  push:
    tags:
      - '*'
  delete:
    tags:
      - '*'
    branches:
      - '*'
  create:
    branches:
      - '*'
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Details
        run: |
          if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
            echo "type=Tag" >> $GITHUB_ENV
            echo "ref=${{ github.event.ref }}" >> $GITHUB_ENV
            echo "url=${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.ref_type }}" == "branch" ]]; then
            echo "type=Branch" >> $GITHUB_ENV
            echo "ref=${{ github.event.ref }}" >> $GITHUB_ENV
            echo "url=${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.ref }}" >> $GITHUB_ENV
          fi
          
      - name: Compose Email Subject
        run: |
          if [[ "${{ github.event.inputs.artifact_uploaded }}" == "true" ]]; then
            echo "subject=Build Completed and Artifact Uploaded to JFrog" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.artifact_uploaded }}" == "false" ]]; then
            if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
              echo "subject=New Tag Created: ${{ github.event.ref }}" >> $GITHUB_ENV
            elif [[ "${{ github.event.ref_type }}" == "branch" ]]; then
              echo "subject=New Branch Created: ${{ github.event.ref }}" >> $GITHUB_ENV
            fi
          fi
          
      - name: Compose Email Body
        id: compose-body
        run: |
          repo_name="${{ github.event.inputs.repo_name }}"
          if [[ "${{ github.event.inputs.artifact_uploaded }}" == "true" ]]; then
            echo "body=An artifact for $repo_name was uploaded to JFrog. You can download it here: ${{ github.event.inputs.artifact_path }}" >> $GITHUB_ENV
          else
            echo "body=A new ${{ env.type }} named '${{ env.ref }}' was created in the repository. You can view it here: ${{ env.url }}. Artifact upload failed or was not attempted." >> $GITHUB_ENV
          fi
            
      - name: Send Gmail Notification
        uses: dawidd6/action-send-mail@v3
        with:
          # server details
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_ID }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          
          # format
          from: ${{ secrets.GMAIL_ID }}
          to: 'neel.dharsandiya@matrixcomsec.com'
          subject: ${{ env.subject }}
          body: ${{ env.body }}
          
