name: Notify on Tag Creation

on:
  push:
    tags:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_ID }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "New Tag Created: ${{ github.ref }}"
          body: |
            A new tag has been created in the repository: ${{ github.repository }}.
            Tag: ${{ github.ref_name }}
            URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
          to: pragya.dayal@matrixcomsec.com
          from: ${{ secrets.GMAIL_ID }}
          

