name: Parasoft SCA of nvrx-rk3588

on:
  workflow_dispatch:  # This triggers the workflow manually

jobs:
  run-cpptest-make:
    name: Analyze project with parasoft C/C++test
    runs-on: self-hosted
    env:  # Environment variables for the entire job
      GIT_HOME_DIR: "/home/neeldharsandiya/neel/selfhostedrunners/actions-runner/ndworkspace"

    # Specifies required permissions for upload-sarif action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Preparing Environment
        run: |
          echo "Set/Export necessary variables..."
          echo "CURRENT_GITHUB_REPOSITORY=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: matrix-comsec-pvt-ltd/ipvs-nvr-app
          submodules: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Download build dependencies from JFrog
        run: |
          echo "Downloading Dependencies..."
          curl -u "admin:cmVmdGtuOjAxOjE3NjQ3NDMzODI6UXFLS2RoZDZrNmpUd2s5M3ptU3hMM2lmQ3lR" -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/Device_Client_Setup_8.7.52.exe" "http://192.168.27.92:8082/artifactory/ipvs-nvr-device-client-prod-release/8.7.52/Device_Client_Setup_8.7.52.exe"
          curl -u "admin:Neel@2822" -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/platform_upgrade.zip" "http://192.168.27.92:8082/artifactory/ipvs-nvrx-platform-prod-release/8.7.0/rk3588h/target/platform_upgrade.zip"
          curl -u "admin:Neel@2822" -o "$GIT_HOME_DIR/$CURRENT_GITHUB_REPOSITORY/$CURRENT_GITHUB_REPOSITORY/src/Application/Build/host.tar.xz" "http://192.168.27.92:8082/artifactory/ipvs-nvrx-platform-prod-release/8.7.0/rk3588h/host/host.tar.xz"

      - name: CleanUp
        run: |
          cd /home/neeldharsandiya/neel/parasoft_workspace/NVR/ && rm -rf NVR_RK3588_NVRH_POC_GITHUB.bdf .cpptest .metadata NVR_RK3588_NVRH_POC_GITHUB/ StaticAnalysisReport/
        
      - name: Compile Project and Collect Data for Code Analysis
        run: |
          cpptesttrace \
          --cpptesttraceOutputFile=/home/neeldharsandiya/neel/parasoft_workspace/NVR/NVR_RK3588_NVRH_POC_GITHUB.bdf \
          '--cpptesttraceTraceCommand=aarch64-linux-gcc|aarch64-linux-g++' \
          --cpptesttraceProjectName=NVR_RK3588_NVRH_POC_GITHUB make svnup appFinal guiFinal BOARD_TYPE=RK3588_NVRH RELEASE_TYPE=QA

      - name: Run Parasoft Static Code Analysis
        run: |
            cpptestcli \
              -exclude '**/Build/**' \
              -data /home/neeldharsandiya/neel/parasoft_workspace/NVR \
              -resource NVR_RK3588_NVRH_POC_GITHUB \
              -config 'dtp://NVR_Matrix_C_OWASP_UPDATED_RULES_FOR_POC_GITHUB' \
              -report /home/neeldharsandiya/neel/parasoft_workspace/NVR/StaticAnalysisReport \
              -bdf /home/neeldharsandiya/neel/parasoft_workspace/NVR/NVR_RK3588_NVRH_POC_GITHUB.bdf \
              -localsettings /home/neeldharsandiya/neel/parasoft_workspace/NVR/localsettings/config.properties \
              -publish
            chmod -R 777 /home/neeldharsandiya/neel/parasoft_workspace/NVR/StaticAnalysisReport
            ls -al /home/neeldharsandiya/neel/parasoft_workspace/NVR/StaticAnalysisReport

      # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
      - name: Upload results (SARIF)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /home/neeldharsandiya/neel/parasoft_workspace/NVR/StaticAnalysisReport/report.sarif
  
      # Uploads an archive that includes all report files (.xml, .html, .sarif, ...).
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CpptestReports
          path: /home/neeldharsandiya/neel/parasoft_workspace/NVR/StaticAnalysisReport/*
